### ISSUE TITLE
bug when running ls command

### ISSUE THREAD

**Issue by helio-frota** [aeshell/mterm#112]
```
lsjava.util.regex.PatternSyntaxException: Unclosed character class near index 9
[0G[2Kls
         ^	at java.util.regex.Pattern.error(Pattern.java:1955)	at java.util.regex.Pattern.clazz(Pattern.java:2548)	at java.util.regex.Pattern.clazz(Pattern.java:2504)	at java.util.regex.Pattern.sequence(Pattern.java:2063)	at java.util.regex.Pattern.expr(Pattern.java:1996)	at java.util.regex.Pattern.compile(Pattern.java:1696)	at java.util.regex.Pattern.<init>(Pattern.java:1351)	at java.util.regex.Pattern.compile(Pattern.java:1028)	at java.lang.String.replaceAll(String.java:2223)	at java_lang_String$replaceAll$6.call(Unknown Source)	at
```
![a](https://cloud.githubusercontent.com/assets/6443576/25729978/954a55ec-310f-11e7-8fed-68a0e7a70774.png)

**Comment by helio-frota** [comment]
Diff result when using aesh 0.66.15
![a](https://cloud.githubusercontent.com/assets/6443576/25785073/513ff370-334e-11e7-8115-e1acdcb3ba89.png)

**Comment by helio-frota** [comment]
looks like we need only solve some scape issues
